# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(743, 554)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setGeometry(QtCore.QRect(50, 10, 661, 111))
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.btn_add = QtWidgets.QPushButton(self.groupBox)
        self.btn_add.setObjectName("btn_add")
        self.gridLayout.addWidget(self.btn_add, 2, 1, 1, 3)
        self.txt_isbn = QtWidgets.QLineEdit(self.groupBox)
        self.txt_isbn.setObjectName("txt_isbn")
        self.gridLayout.addWidget(self.txt_isbn, 0, 0, 1, 1)
        self.txt_author = QtWidgets.QLineEdit(self.groupBox)
        self.txt_author.setObjectName("txt_author")
        self.gridLayout.addWidget(self.txt_author, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.txt_title = QtWidgets.QLineEdit(self.groupBox)
        self.txt_title.setObjectName("txt_title")
        self.gridLayout.addWidget(self.txt_title, 0, 4, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 5, 1, 1)
        self.lbl_author_error = QtWidgets.QLabel(self.groupBox)
        self.lbl_author_error.setText("")
        self.lbl_author_error.setObjectName("lbl_author_error")
        self.gridLayout.addWidget(self.lbl_author_error, 1, 2, 1, 1)
        self.lbl_title_error = QtWidgets.QLabel(self.groupBox)
        self.lbl_title_error.setText("")
        self.lbl_title_error.setObjectName("lbl_title_error")
        self.gridLayout.addWidget(self.lbl_title_error, 1, 4, 1, 1)
        self.lbl_isbn_error = QtWidgets.QLabel(self.groupBox)
        self.lbl_isbn_error.setText("")
        self.lbl_isbn_error.setObjectName("lbl_isbn_error")
        self.gridLayout.addWidget(self.lbl_isbn_error, 1, 0, 1, 1)
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 160, 681, 381))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.table_books = QtWidgets.QTableView(self.layoutWidget)
        self.table_books.setObjectName("table_books")
        self.verticalLayout.addWidget(self.table_books)
        self.btnBorrow= QtWidgets.QPushButton(self.layoutWidget)
        self.btnBorrow.setObjectName("btnBorrow")
        self.verticalLayout.addWidget(self.btnBorrow)
        self.btn_delete = QtWidgets.QPushButton(self.layoutWidget)
        self.btn_delete.setObjectName("btn_delete")
        self.verticalLayout.addWidget(self.btn_delete)
        self.btnBorrowedBooks = QtWidgets.QPushButton(self.layoutWidget)
        self.btnBorrowedBooks.setObjectName("btnBorrowedBooks")
        self.verticalLayout.addWidget(self.btnBorrowedBooks
)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox.setTitle(_translate("Dialog", "اضافه کردن کتاب"))
        self.btn_add.setText(_translate("Dialog", "اضافه به کتابخانه"))
        self.label_3.setText(_translate("Dialog", "Isbn"))
        self.label_2.setText(_translate("Dialog", "نویسنده :"))
        self.label.setText(_translate("Dialog", "عنوان کتاب : "))
        self.btnBorrow.setText(_translate("Dialog", "قرض گرفتن کتاب"))
        self.btn_delete.setText(_translate("Dialog", "حذف کتاب انتخاب شده"))
        self.btnBorrowedBooks.setText(_translate("Dialog", "کتاب های قرضی"))
